name: thumbnail_generator
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  gap: ^3.0.1
  google_fonts: ^6.1.0
  http: ^1.2.0
  image_picker: ^1.0.7
  video_player: ^2.8.2
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
